name: 'Python Safety Check'
description: 'Helps to find known security vulnerabilities in your python application'
author: aufdenpunkt

jobs:
 run in the workflow
  runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2
      -name: check the security of python source code
inputs:
  safety_args:
    description: Optional Safety script parameters. (e.g. --ignore=1234 or -i 1234)
    default: ''
  scan_requirements_file_only:
    description: Set true to scan required python packages without installing them.
    default: 'false'
branding:
  icon: 'shield'
  color: 'green'